# Generated by Django 4.1.3 on 2022-12-11 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='audio_file',
            field=models.FileField(upload_to='audio', validators=[django.core.validators.FileExtensionValidator(['mp3', 'm4a', 'aac', 'wav'])], verbose_name='fichier audio'),
        ),
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(max_length=60, unique=True, verbose_name='titre'),
        ),
    ]
